### PR TITLE
Admin test list news

### PR DESCRIPTION
**Pull request by duocnguyenc**

### CODE REVIEW

**Comment by ghost** [comment]
Kiểm tra button trang nữa

**Comment by at-thinhnguyen** [comment]
[LGTM](http://lgtm.in/i/Myt3ozoOp)

**Comment by at-thinhnguyen** [comment]
[LGTM](https://lh6.googleusercontent.com/QILe3Bou6hqn2QigMW6PL-KLEP3VkzJnxOXoW5O73ZPg0_p8Y1q0ecFPjC04Yn0Cb7OQ1j8HJNQYxfQ=w1440-h712)

**Comment by ghost** [comment]
LGTM

[LGTM](http://sv1.upsieutoc.com/2017/08/16/i292pimgpsh_fullsize_distr.jpg)

**Pull request merged**
